DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  address VARCHAR NOT NULL,
  neighborhood VARCHAR NOT NULL,
  borrower BOOLEAN NOT NULL,
  lender BOOLEAN NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  cash_balance_cents INTEGER NOT NULL,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);